site_name: mojang
site_author: summer
repo_name: summer/mojang
repo_url: https://github.com/summer/mojang
edit_uri: ""

theme:
  name: "material"
  features:
    - navigation.instant
    - navigation.sections
    - navigation.expand
    - navigation.top

extra_css:
  - css/extra.css

plugins:
  - search
  - mkdocstrings:
      custom_templates: docs/templates
      watch:
        - mojang

nav:
  - Getting Started: "index.md"
  - API Methods: "api.md"

  - META:
      - "License": "license.md"
      - "Legal": "legal.md"

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.magiclink
  - pymdownx.saneheaders
  - pymdownx.superfences
  - toc:
      permalink: "#"

